# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.User', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
