# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170606_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, 'Не прочитано'), (True, 'Прочитано')], verbose_name='Статус')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Post', verbose_name='Пост')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, 'Не подписан'), (True, 'Подписан')], verbose_name='Статус подписки')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog', verbose_name='Блог')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.User', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='markpost',
            name='subscribe_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.SubscribeBlog', verbose_name='Подписка'),
        ),
    ]
