# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20170607_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeblog',
            name='status',
        ),
    ]
