# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_subscribeblog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='markpost',
            name='subscribe_blog',
        ),
        migrations.AddField(
            model_name='markpost',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID пользователя'),
        ),
    ]
